---

- name: remove haproxy.cfg file
  file:
    path: /etc/haproxy/haproxy.cfg
    state: absent

- name: Check that the haproxy.cfg doesn't exist
  stat:
    path: /etc/haproxy/haproxy.cfg
  register: stat_result

- debug:
    msg: "/etc/haproxy/haproxy.cfg doesn't exist"
  when: stat_result.stat.exists == false

- name: "Install haproxy.cfg"
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: "Restart HAProxy"
  systemd:
    state: reloaded
    name: haproxy