---

- name: "Create HAProxy directories"
  file:
    path: /etc/haproxy
    state: directory
    mode: 0755

- name: "Install haproxy.cfg"
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: "Restart HAProxy"
  systemd:
    state: reloaded
    name: haproxy
