---

# webserver as lighthttpd Docker container

- name: "Create webserver (lighthttpd) directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
      - "{{ webserver_path_local }}"
