#- include_vars:
#    dir: 'vars'

- name: "Create Consul group"
  group:
    name: consul
    state: present

- name: "Create Consul user"
  user:
    name: consul
    comment: "Consul user"
    group: consul

- name: Create Consul config directories
  file:
    path: "/etc/consul.d/{{ item }}"
    state: directory
    mode: 0755
  with_items:
      - bootstrap
      - server
      - client

- name: "Create Consul data directory"
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: consul
    group: consul
    mode: 0755


# ------------------------------------------------------------------------------
#                       CONSUL SERVERS

- name: "Show group_vars - ansible_hostname"
  debug:  msg="{{ item['name'] }} has flag {{ item['bootstrap_flag'] }}"
  with_items: "{{ consul_server_vars }}"

- name: "Show group_vars - ip addresses"
  debug: >
    msg="{{ hostvars[item]['ansible_eth1']['ipv4']['address']
          | default( hostvars[item]['ansible_lo']['ipv4']['address'] ) }}"
  with_items: "{{ groups['consul-servers'] }}"
#  loop_control:
#    label: "{{item.name}}"
### TESTING OUT LOOP_CONTROL - LABEL ###


- name: "Copy service config for each server into /etc/consul.d/server"
  template:
    src: templates/server/config.json.j2
    dest: /etc/consul.d/server/config.json
    owner: consul
    group: consul
    mode: 0644
  when: "item['hostname'] == inventory_hostname"
  with_items: "{{ consul_server_vars }}"

#- name: "Show comparison between current host and host in consul-master"
#  debug:  msg="{{ groups['consul-master'][0] }} / {{ item['hostname'] }} / {{ inventory_hostname }}"
#  with_items: "{{ consul_server_vars }}"

- name: "Copy bootstrap config for initial server /etc/consul.d/bootstrap"
  template:
    src: templates/bootstrap/config.json.j2
    dest: /etc/consul.d/bootstrap/config.json
    owner: consul
    group: consul
    mode: 0644
  when: "groups['consul-master'][0] == item['hostname'] == inventory_hostname"
  with_items: "{{ consul_server_vars }}"

#  THIS IS PROB THE CORRECT WAY TO PERFORM THE CONDITIONAL CHECK ABOVE
#  when:
#    - groups['consul-master'][0] == item['hostname']
#    - item['hostname'] == inventory_hostname"
# AND ALSO REQUIRE ADDITIONAL WHEN STATEMENT #
#    - item['hostname'] is defined

- name: "Copy upstart file to client host"
  template:
    src: templates/server/consul.conf.j2
    dest: /etc/init/consul.conf
    owner: consul
    group: consul
    mode: 0644
  when: "'consul-servers' in group_names"

# ------------------------------------------------------------------------------
#                       CONSUL CLIENTS

- name: "Show group_vars - ip addresses"
  debug:  msg="{{ hostvars[item]['ansible_eth1']['ipv4']['address'] }}"
  with_items: "{{ groups['consul-clients'] }}"

- name: "Copy service config for each server into /etc/consul.d/client"
  template:
    src: templates/client/config.json.j2
    dest: /etc/consul.d/client/config.json
    owner: consul
    group: consul
    mode: 0644
  when: "item['hostname'] == inventory_hostname"
  with_items: "{{ consul_client_vars }}"

- name: "Create Consul ui directory on clients"
  file:
    path: "{{ ui_dir }}"
    state: directory
    owner: consul
    group: consul
    mode: 0755
  when: "'consul-clients' in group_names"
# ^^^ USE THIS IDIOM ABOVE FOR REFERENCING A HOST IN A PARTICULAR GROUP

- name: "Copy upstart file to client host"
  template:
    src: templates/client/consul.conf.j2
    dest: /etc/init/consul.conf
    owner: consul
    group: consul
    mode: 0644
  when: "'consul-clients' in group_names"