- name: "Install Python packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - python
  - python-setuptools
  - python-pip

- include: docker-py.yml # Requires python-pip
- include: boto.yml # Requires python-pip
- include: passlib.yml #Requires python-pip
- include: bcrypt.yml #Requires python-pip
