---

- name: "Create Docker directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ compose_path_local }}"
    - "{{ compose_path_local }}{{ docker_compose_dir }}"

- name: "Copy docker-compose.yml files to client hosts"
  template:
    src: templates/client/docker-compose.yml.j2
    dest: "{{ compose_path_local }}{{ docker_compose_dir }}/docker-compose.yml"
    owner: docker
    group: docker
    mode: 0644
  when: "'consul-clients' in group_names"  
  
- name: "Copy docker-compose.yml files to server hosts"
  template:
    src: templates/server/docker-compose.yml.j2
    dest: "{{ compose_path_local }}{{ docker_compose_dir }}/docker-compose.yml"
    owner: docker
    group: docker
    mode: 0644
  when: "'consul-master' in group_names" 
  