---

- name: Install Epel-Release, Docker Engine, Python Tools
  hosts: all
  remote_user: centos
  become: True
  gather_facts: True
  roles:
    - epel
    - python
    - docker
    - docker-registry

