---

- name: Install Epel-Release, Docker Engine, Python Tools
  hosts: all
  remote_user: centos
  become: True
  gather_facts: True
  roles:
    - epel
    - { role: "python", python_package: "pip", package_manager: "yum" }
    - { role: "python", python_package: "bcrypt", package_manager: "yum" }
    - { role: "python", python_package: "docker-py", package_manager: "yum" }
    - { role: "python", python_package: "passlib", package_manager: "yum" }
    - { role: "python", python_package: "boto", package_manager: "yum" }
    - geerlingguy.git
    - geerlingguy.certbot
    - haproxy
    - docker
    - docker-registry


