
- hosts: "local"
  remote_user: jack
  become: True
  gather_facts: False
  roles:
    - "os-local"



- hosts: "local-vagrant"
  remote_user: vagrant
  become: False
  gather_facts: True
  vars:
    mode: provision_mode
  roles:
    - "vagrant-consul"

#- hosts: "local-vagrant"
#  remote_user: jack
#  become: False
#  gather_facts: False
#  vars:
#    provision_mode: check
#  roles:
#    - "vagrant-consul"



- hosts: "consul-hosts"
  remote_user: vagrant
  become: True
  gather_facts: True
  roles:
    - { role: "python", python_package: "redis-py", package_manager: "apt" }
    - "docker"
    - "consul"


- hosts: "db-servers"
  remote_user: vagrant
  become: True
  gather_facts: True
  roles:
    - "deploy-service-containers"
    - "deploy-netdata-monitor"


- hosts: "frontend-clients"
  remote_user: vagrant
  become: True
  gather_facts: True
  roles:
    - "deploy-service-containers"
    - "deploy-netdata-monitor"

