
- hosts: "local"
  remote_user: jack
  become: True
  gather_facts: False
  roles:
    - "os-local"

- hosts: "local"
  remote_user: jack
  become: False
  gather_facts: False
  roles:
    - "vagrant-consul"

- hosts: "consul-servers"
  remote_user: vagrant
  become: True
  gather_facts: True
  roles:
    - "consul"
    - "vagrant-docker"

- hosts: "consul-clients"
  remote_user: vagrant
  become: True
  gather_facts: True
  roles:
    - "consul"
    - "vagrant-docker"
