# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify a custom Vagrant box for the demo
#DEMO_BOX_NAME = ENV['DEMO_BOX_NAME'] || "debian/jessie64"
DEMO_BOX_NAME = ENV['DEMO_BOX_NAME'] || "custom/trusty64"

# Vagrantfile API/syntax version.
# NB: Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = DEMO_BOX_NAME

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
  end


# RANDOM NUMBER FUNCTION FOR PORTS #
def random_num(lowest)
        highest = lowest+19
	r = Random.new
	ssh_port = r.rand(lowest...highest)
   	return ssh_port
end



# --------------------- SETUP SSH -----------------------------#
  # ssh settings
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/ansible_id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "~/.ssh/ansible_id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "shell", inline: <<-EOC
    sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
    sudo service ssh restart
  EOC

# ---------------- DISABLE USB -------------------------------#
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "on"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end
# ----------------------------------------------------------- #

  config.vm.synced_folder ".", "/vagrant", disabled: true


# Servers
  config.vm.define "n1" do |n1|
      n1.vm.hostname = "n1"
      n1.vm.network "private_network", ip: "172.20.20.10"
      n1.vm.network "forwarded_port", guest: 22, host: random_num(2020), id: 'ssh', auto_correct: true
  end

  config.vm.define "n2" do |n2|
      n2.vm.hostname = "n2"
      n2.vm.network "private_network", ip: "172.20.20.11"
      n2.vm.network "forwarded_port", guest: 22, host: random_num(2040), id: 'ssh', auto_correct: true
  end

  config.vm.define "n3" do |n3|
      n3.vm.hostname = "n3"
      n3.vm.network "private_network", ip: "172.20.20.12"
      n3.vm.network "forwarded_port", guest: 22, host: random_num(2060), id: 'ssh', auto_correct: true
  end


# Clients
  config.vm.define "c1" do |c1|
      c1.vm.hostname = "c1"
      c1.vm.network "private_network", ip: "172.20.20.20"
      c1.vm.network "forwarded_port", guest: 22, host: random_num(2080), id: 'ssh', auto_correct: true
  end

    config.vm.define "c2" do |c2|
      c2.vm.hostname = "c2"
      c2.vm.network "private_network", ip: "172.20.20.21"
      c2.vm.network "forwarded_port", guest: 22, host: random_num(2100), id: 'ssh', auto_correct: true
  end

    config.vm.define "c3" do |c3|
      c3.vm.hostname = "c3"
      c3.vm.network "private_network", ip: "172.20.20.22"
      c3.vm.network "forwarded_port", guest: 22, host: random_num(2120), id: 'ssh', auto_correct: true
  end

end
