
data_center: "local-dc-1"
data_dir: "/var/consul"


consul_server_vars:
  - name: "n1"
    server_hostname: "n1.local"
    server_flag: "true"
    bootstrap_flag: "false"
    encryption_key: "dabbyhNw7FNaFIxvslCebA=="
  - name: "n2"
    server_hostname: "n2.local"
    server_flag: "true"
    bootstrap_flag: "false"
    encryption_key: "dabbyhNw7FNaFIxvslCebA=="
  - name: "n3"
    server_hostname: "n3.local"
    server_flag: "true"
    bootstrap_flag: "false"
    encryption_key: "dabbyhNw7FNaFIxvslCebA=="


consul_client_vars:
  - name: "c1"
    client_hostname: "c1.local"
    server_flag: "true"
    bootstrap_flag: "false"
    encryption_key: "dabbyhNw7FNaFIxvslCebA=="
  - name: "c2"
    client_hostname: "c2.local"
    server_flag: "true"
    bootstrap_flag: "false"
    encryption_key: "dabbyhNw7FNaFIxvslCebA=="
  - name: "c3"
    client_hostname: "c3.local"
    server_flag: "true"
    bootstrap_flag: "false"
    encryption_key: "dabbyhNw7FNaFIxvslCebA=="