

- name: "Create NetData directory for cache volume"
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    
- name: "Create Docker directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
      - "{{ netdata_path_local }}{{ docker_compose_dir }}"
      - "{{ netdata_path_local }}{{ netdata_cache_dir }}"
      - "{{ netdata_path_local }}"

- name: "Copy docker-compose.yml to hosts"
  template:
    src: templates/docker-compose.yml.j2
    dest: "{{ netdata_path_local }}{{ docker_compose_dir }}/docker-compose.yml"
    mode: 0644


- name: "docker-compose up command"
  command: docker-compose up -d
  args:
    chdir: "{{ netdata_path_local }}{{ docker_compose_dir }}"





# CLI REF:
#  sudo docker run -d --cap-add SYS_PTRACE \
#                   -v /proc:/host/proc:ro \
#                   -v /sys:/host/sys:ro \
#                   -v /var/lib/docker-netdata/cache/netdata:/var/cache/netdata \
#                   -v /var/run/docker.sock:/var/run/docker.sock \
#                   -p 19999:19999 \
#                   titpetric/netdata